### ISSUE TITLE
TypeError: config.rule[ind].test is not a function

### ISSUE THREAD

**Issue by yiss** [vifird/gulp-connect-reproxy#1]
Whenever I try to launch gulp-connect I get this error.
 if(config.rule[ind].test(url)){
                                                ^
TypeError: config.rule[ind].test is not a function
    at \node_modules\gulp-connect-reproxy\index.js:57:49
    at FSReqWrap.oncomplete (fs.js:114:15)

**Comment by lanistor** [comment]
Could you show me more code?

**Comment by yiss** [comment]
gulp.task('server', function () {
    connect.server({
        port: 9000,
        root: buildFolder,
        middleware: function (connect,options) {

            options.rule= '/api';
            options.server = '127.0.0.1:8080';
            var proxy = new Reproxy(options);

            return [proxy];
        }
    });
});
